### ISSUE TITLE
Fixed Nav Bar

### ISSUE THREAD

**Issue by sftbb** [creativetimofficial/material-dashboard#2]
isn't there any way to have fixed nav bar at top

**Comment by dragosct10** [comment]
1. First you need to add the class “navbar-fixed ” on the tag nav and move your structure outside of the div with class “main-panel” like this:

```html
<div class="sidebar" data-color="purple" data-image="../assets/img/sidebar-1.jpg">
        ....
    </div>

    <nav class="navbar navbar-color-on-scroll navbar-transparent navbar-fixed">
        <div class="container-fluid">
            ....
        </div>
    </nav>

    <div class="main-panel">
        <-- .navbar used to be here, but was moved outside of this div -->
        ....
    </div>
```

2. Go to your scss partial _navbars.scss and add the following properties to your class “.navbar-fixed”:

```css
.navbar-fixed{
    position: fixed;
    z-index: 1032;
    right: 0;
    width: 100%;
}

@media (min-width: 991px){
    .navbar-fixed{
        width:calc(100% - 260px);
    }
}

```

3. Compile your scss with Koala assets/scss/material-dashboard.scss

4. Go to `assets/js/ material-dashboard.js ` and put the following lines of code on line 67, then go on line 125 and replace `$(document)` with `$('.main-panel') `: 
```js
if($('.navbar-color-on-scroll').length != 0){
        $('.main-panel').on('scroll', md.checkScrollForTransparentNavbar);
    }
```
