### ISSUE TITLE
sidebar-menu-on-left!

### ISSUE THREAD

**Issue by dragosct10** [creativetimofficial/material-dashboard#3]
1.First you must to go on html page and add to body tag the class `menu-on-left`.

2.Second go to `assets/sass/md/_responsive.scss` and add the following lines of code:
```css
@media (max-width: 991px){
     .menu-on-left{
        &.nav-open{
            .main-panel,
            .wrapper-full-page,
            .navbar-fixed > div{
                @include transform-translate-x(260px);
            }

            .sidebar,
            .off-canvas-sidebar{
                @include transform-translate-x(0px);
            }
        }

        .sidebar,
        .off-canvas-sidebar{
            left: 0;
            right: auto;
            @include transform-translate-x(-260px);
        }
    }
}
```
3. Compile your scss with [Koala](http://koala-app.com/) assets/scss/paper-dashboard.scss.

4. Go to `assets/js/material-dashboard.js` and add the following code on line 84 and line 97, then go to the following lines: 197,  221  and 233. You have to replace `$('html')` with `$('body')`:
```js
line 84: if( $(window).width() <= 991 && $('body').hasClass('menu-on-left') ){
        $('.main-panel').css('position','fixed');
    }

line 97: if( $(window).width() <= 991 && $('body').hasClass('menu-on-left') ){
        $('.main-panel').css('position','fixed');
    } else {
        $('.main-panel').css('position','');
    }

```
